name: Release Theme

on:
  push:
    branches:
      - master   # or 'main' if that's your default branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: WordPress Release Creator
        uses: aether-wp/create-public-release@v0.6.3
        with:
          path: 'wpex-tetris'                       # Path to your theme folder
          name: 'WordPress Theme Release'           # Name for the GitHub release (optional)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
