name: Release Theme

on:
  push:
    branches:
      - master   # or 'main' if that's your default branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: WordPress Release Creator
        uses: aether-wp/create-public-release@v0.6.3
        with:
          name: 'WordPress Theme Release'                # Optional: custom release name
          token: ${{ secrets.GITHUB_TOKEN }}             # Required: GitHub token for authentication
